export const GET_POKEMON = "GET_POKEMON";

export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";

export const GET_POKEMON_FAILURE = "GET_POKEMON_FAILURE";

export const GET_POKEMON_DETAILS_REQUEST = "GET_POKEMON_DETAILS_REQUEST";

export const GET_POKEMON_DETAILS_SUCCESS = "GET_POKEMON_DETAILS_SUCCESS";

export const GET_POKEMON_DETAILS_FAILURE = "GET_POKEMON_DETAILS_FAILURE";

export const SEARCH = "SEARCH";

export const GET_ALL_POKEMON = "GET_ALL_POKEMON";

export const GET_ALL_POKEMON_RESULTS = "GET_ALL_POKEMON_RESULTS";

export const SORT = "SORT";

export const SORT_REVERSE = "SORT_REVERSE";

export const CLOSE_APPLICATION = "CLOSE_APPLICATION";

export const OPEN_RESOURCE_MONITOR = "OPEN_RESOURCE_MONITOR";

export const RESTART_APPLICATION = "RESTART_APPLICATION";

export const UPDATE_RIGHT_PANEL = "UPDATE_RIGHT_PANEL";

export const UPDATE_LEFT_PANEL = "UPDATE_LEFT_PANEL";
